version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_NAME: ecommerce
      DB_USER: user
      DB_PASSWORD: password
      JWT_SECRET: your_jwt_secret
    depends_on:
      - db

volumes:
  db-data:
